name: CI checks

on: [push, pull_request]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up git private repo access
        run: |
          git config --global url."https://${{ secrets.REPO_TOKEN }}@github.com/".insteadOf ssh://git@github.com
          git config --global url."https://${{ secrets.REPO_TOKEN }}@github.com".insteadOf https://github.com
      - uses: actions/checkout@v3
      - name: Run tests
        run: cargo test --verbose --release --features experimental,zeroize
        env:
          CARGO_NET_GIT_FETCH_WITH_CLI: true

  wasm:
    name: Check wasm target ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - wasm32-unknown-unknown
          - wasm32-wasi
    steps:
      - name: Set up git private repo access
        run: |
          git config --global url."https://${{ secrets.REPO_TOKEN }}@github.com/".insteadOf ssh://git@github.com
          git config --global url."https://${{ secrets.REPO_TOKEN }}@github.com".insteadOf https://github.com
      - uses: actions/checkout@v3
      - run: rustup target add ${{ matrix.target }}
      - run: cargo fetch
      - name: Build
        run: >
          cargo build
          --verbose
          --target ${{ matrix.target }}
          --no-default-features
          --features groups,pairings,alloc

  bitrot:
    name: Bitrot check
    runs-on: ubuntu-latest
    steps:
      - name: Set up git private repo access
        run: |
          git config --global url."https://${{ secrets.REPO_TOKEN }}@github.com/".insteadOf ssh://git@github.com
          git config --global url."https://${{ secrets.REPO_TOKEN }}@github.com".insteadOf https://github.com
      - uses: actions/checkout@v3
      # Build benchmarks and all-features to prevent bitrot
      - name: Build benchmarks
        run: cargo build --benches --examples --all-features

  doc-links:
    name: Intra-doc links
    runs-on: ubuntu-latest
    steps:
      - name: Set up git private repo access
        run: |
          git config --global url."https://${{ secrets.REPO_TOKEN }}@github.com/".insteadOf ssh://git@github.com
          git config --global url."https://${{ secrets.REPO_TOKEN }}@github.com".insteadOf https://github.com
      - uses: actions/checkout@v3
      - run: cargo fetch
      # Requires #![deny(rustdoc::broken_intra_doc_links)] in crate.
      - name: Check intra-doc links
        run: cargo doc --document-private-items

  clippy:
    name: Rustfmt
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Set up git private repo access
        run: |
          git config --global url."https://${{ secrets.REPO_TOKEN }}@github.com/".insteadOf ssh://git@github.com
          git config --global url."https://${{ secrets.REPO_TOKEN }}@github.com".insteadOf https://github.com
      - uses: actions/checkout@v3
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo xclippy
